apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdf
  template:
    metadata:
      labels:
        app: sdf
    spec:
      containers:
      - image: okteto.dev/sdf:latest
        name: sdf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f49ceccb-bc0f-47d2-84cb-f9e44fb01811"
        - name: Vless_Path
          value: "/erdgfh3563s"
        - name: Vmess_UUID
          value: "f49ceccb-bc0f-47d2-84cb-f9e44fb01811"
        - name: Vmess_Path
          value: "/ch45hhsd3"
        - name: Share_Path
          value: "/v2link"
